name: Cloud Build

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: 'Set up Cloud SDK'
        run: |
          echo ${{ secrets.GCP_SA_KEY }} > ${HOME}/gcloud-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: 'Build Docker image'
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/cloudrun-python-poc .

      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy cloudrun-python-poc \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/cloudrun-python-poc \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated